---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vinod
spec:
  schedule: '* * * * *'
  jobTemplate: 
    metadata:
      name: vinod1
    spec:
      backoffLimit: 2
      template:
        metadata:
          name: vinod22
        spec:
          restartPolicy: OnFailure
          containers:
            - name: vinod77
              image: ubuntu:latest
              command:
                - sleep
                - 10s
      




