---
apiVersion: batch/v1
kind: Job
metadata:
  name: vinod
spec:
  backoffLimit: 5
  template:
    metadata:
      name: vinod2
    spec:
      restartPolicy: OnFailure
      containers:
        - name: vinod3
          image: alpine:latest
          command:
            - sleep
            - 10s
