---
apiVersion: v1
kind: Service
metadata: 
  name: loadbalancer
spec:
  ports: 
    - name: alpine-ld
      port: 80
      protocol: TCP
      targetPort: 80
  selector: 
    app: alpine
  type: LoadBalancer
    
