---
apiVersion: v1
kind: Pod
metadata:
  name: restartonfilure
spec:
  restartPolicy: OnFailure
  containers:
    - name: one
      image: alpine:latest
      command:
        - sleep
        - 3SM

---
apiVersion: v1
kind: Pod
metadata:
  name: restartonfilure2
spec:
  restartPolicy: OnFailure
  containers:
    - name: one
      image: alpine:latest
      command:
        - sleep
        - 3s
